services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog

    ports:
      - "1025:1025" 
      - "8025:8025" # Web UI

    restart: unless-stopped

  notification-database:
    image: postgres:16
    container_name: notification-database

    environment:
      POSTGRES_DB: ${NOTIFICATION_DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

    ports:
      - "5438:5432"

    volumes:
      - notification-db-data:/var/lib/postgresql/data

volumes:
  notification-db-data: