spring.application.name=notification-service
server.port=8086

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}
eureka.client.fetch-registry=true


# RABBIMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:rota-facil}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}