# SPRING
spring.application.name=notification-service
server.port=8086
server.servlet.context-path=/notifications
spring.config.import=optional:file:.env[.properties]

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.fetch-registry=true


# RABBIMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:rota-facil}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

# RABBITMQ TRANSPORT
rabbitmq.transport.exchange=${RABBITMQ_TRANSPORT_EXCHANGE:transport.events}
# queues
rabbitmq.notification.trip.cancelled.queue=${RABBITMQ_NOTIFICATION_TRIP_CANCELLED_QUEUE:notification.trip.cancelled.queue}
# routing key
rabbitmq.trip.cancelled.routing.key=${RABBITMQ_TRIP_CANCELLED_ROUTING_KEY:trip.cancelled}

# OBSERVABILITY
# traces
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# metrics
management.otlp.metrics.export.enabled=true

# collector
management.otlp.tracing.endpoint=${COLLECTOR_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
management.otlp.metrics.export.url=${COLLECTOR_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}

# email
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Thymeleaf
thymeleaf.prefix=classpath:/templates/
thymeleaf.suffix=.html
thymeleaf.mode=HTML
thymeleaf.cache=false


# SWAGGER
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
